config/routes.rb
Rails.application.routes.draw do
  instance_exec(
    :packager, 'v1/github/packager?push=enabled',
    &FissionApp::Repositories.repositories_routes
  )

  instance_exec(
    :packager,
    &FissionApp::Jobs.jobs_routes
  )

  namespace :packager do
    get 'dashboard', :to => 'dashboard#index', :as => :dashboard
    resources :repository, :only => [:show]
  end
end

app/controllers/packager/dashboard_controller.rb
class Packager::DashboardController < ApplicationController

  def index
    @accounts = [@account]
    respond_to do |format|
      format.js do
        flash[:error] = 'Unsupported request!'
        javascript_redirect_to packager_dashboard_path
      end
      format.html do
        jobs_dataset = Job.dataset_with(
          :scalars => {
            :status => ['status'],
            :job_name => ['data', 'router', 'action'],
            :repository_name => ['data', 'github', 'repository', 'full_name']
          }
        ).where(
          :job_name => @product.internal_name,
          :id => Job.current_dataset.select(:id)
        )
        @data = Hash[
          @accounts.map do |acct|
            [
              acct,
              Hash[
                @product.repositories_dataset.where(:account_id => acct.id).all.map do |repo|
                  [repo, jobs_dataset.where(:repository_name => repo.name)]
                end
              ]
            ]
          end
        ]
      end
    end
  end

end

app/controllers/packager/jobs_controller.rb
class Packager::JobsController < ApplicationController

end

app/controllers/packager/repository_controller.rb
class Packager::RepositoryController < ApplicationController

  before_action do
    @repo = current_user.run_state.current_account.repositories_dataset.where(:id => params[:id]).first
  end

  def show
    @github = github(:bot)
    @table_headers = ['Package', 'Release', 'Version', 'Download count', 'Size', 'Author', 'Published']
    @table_data    = []

    vc = view_context
    @github.releases(@repo.name).each do | release |
      release.assets.each do | asset |
        @table_data <<
          [vc.link_to(asset.name, asset.browser_download_url),
           release.name,
           vc.link_to(release.tag_name, release.html_url),
           asset.download_count,
           vc.number_to_human_size(asset.size),
           vc.link_to(release.author.login,release.author.html_url),
           "#{release.published_at.strftime("%m-%d-%Y")} (#{vc.time_ago_in_words(release.published_at)} ago)"]
      end
    end
  end

end

app/views/packager/dashboard/index.html.haml
- id = 'packager'
- content_for(:header_link) do
  %a{ :href => packager_repositories_path }
    %span.glyphicon.glyphicon-cog

:ruby
  content_for(:container) do
    render(
      :partial => 'layouts/panel',
      :locals  => {
        :id => "#{id}-panel",
        :heading => 'Packager Dashboard',
        :panel_content => @data.map{ |acct, repos|
          header_data = [acct.name, content_for(:header_link)]
          data = repos.map { |repo, jobs| [link_to(repo.name, packager_repository_path(repo.id)), jobs.count] }

          render(:partial => 'layouts/table', :locals => { :header_data => header_data, :data => data })
        }.join.html_safe
      }
    )
  end

= render(:partial => 'layouts/container', :locals => { :container_class => "#{id}-dashboard", :container_id => id })

app/views/packager/repository/show.html.haml
- id = 'packager'

:ruby
  content_for(:container) do
    render(
      :partial => 'layouts/panel',
      :locals  => {
        :id => "#{id}-panel",
        :heading => @repo.name,
        :panel_content => render(:partial => 'layouts/table', :locals => { :header_data => @table_headers, :data => @table_data })
      }
    )
  end

= render(:partial => 'layouts/container', :locals => { :container_class => "#{id}-show", :container_id => id })